### ISSUE TITLE
引用文献格式与编写规则中不符

### ISSUE THREAD

**Issue by Zardinality** [szcf-weiya/zju-thesis#10]
感谢开源这么棒的工作！
第一个问题是，正文中的引文标注采用了姓氏+出版年制，但文后的引用文献却编了号。编写规则中的相关说明如下：
![image](https://user-images.githubusercontent.com/13702822/39957659-267a9812-5629-11e8-84bb-ace1ad777bca.png)
![image](https://user-images.githubusercontent.com/13702822/39957669-40d78fda-5629-11e8-8d7a-c80c185ebaf0.png)
请问有没有让正文中的引文标注使用编号制的方法？
第二个问题是，我编写规则中规定参考文献表应用五号宋体，而我编译出来的看起来跟示例...不怎么像，如下：
![image](https://user-images.githubusercontent.com/13702822/39957683-a5075148-5629-11e8-8a0e-f14a7c075dbf.png)
>示例

![image](https://user-images.githubusercontent.com/13702822/39957684-ad3d3274-5629-11e8-94c6-f6bb87491412.png)
>编译结果

如果这两者其实是相同的字体，请忽略这个问题。

先行感谢

**Comment by szcf-weiya** [comment]
您好，欢迎关注本模板！
首先回答第一个问题，修改成编号格式是很容易的，下一次更新时，用户可以通过参数选择编号格式或者著作者格式；
关于第二个问题，之前也没有完全按照编写规则的示例来调整格式，一来是觉得编写规则中并没有明确说明文献的具体格式，二来这种格式后期改起来应该不是很难，目前采用的格式是 APA。

**Comment by Zardinality** [comment]
@szcf-weiya 谢谢回答。关于第二个问题，编写规则规定了文献列表的具体格式，不过我也觉得没有必要完全遵守，APA 就挺好的。我只是对字体是否是宋体五号有些疑虑。
现在关闭这个 issue ，因为我的问题得到解答。

**Comment by szcf-weiya** [comment]
@Zardinality 终于腾出时间来调格式了。首先很抱歉，上次第一个问题回答错了，之前文献默认格式是 `authoryear`，而非 `APA`。不过现在已经换成了 `APA`，这一点问过老师，称 `APA` 是合适的。

**Comment by szcf-weiya** [comment]
@Zardinality 因为 APA 要用到 `babel` 包，导致之前自定义的中文表、图等名称失效了，又变为英文了，详见 Issue #14，预计在下个版本改过来。
