### ISSUE TITLE
正文字体加粗

### ISSUE THREAD

**Issue by zxqaiycx** [szcf-weiya/zju-thesis#12]
正文字体加粗

**Comment by szcf-weiya** [comment]
使用 `\bfxs{}`

**Comment by luzai** [comment]
谢谢你的论文模板！
`\xeCJKsetup{AutoFakeBold=0}` 可以避免复制中文出来的时候是乱码或者不能复制的问题，便于检索查重，但是就没有不能使用伪粗体了。
如果`\setCJKmainfont[BoldFont={\heifont}]{\fangfont}`，那么粗体其实不是fangsong字体的粗体。
不知道有没有好的方法，能使用fangsong粗体，又能复制。
（我的设置是\documentclass[fangfont=FangSong,heifont=SimHei]{zju-thesis}）

**Comment by szcf-weiya** [comment]
非常感谢！
