### ISSUE TITLE
小节没有奇数页开头

### ISSUE THREAD

**Issue by Edmund-Shi** [szcf-weiya/zju-thesis#17]
在论文中，各个小节都需要奇数页开始，这会影响到页眉的内容。

例如以下内容均需要奇数页开头：
* 毕业论文承诺书
* 致谢
* 摘要（中英文）
* 目录

而模版中还没有实现该功能。

**Comment by Edmund-Shi** [comment]
参考了[这篇资料](http://www.tex.ac.uk/FAQ-reallyblank.html)，通过`\newcommand`的方法解决了这个问题。

增加以下代码：
```latex
\let\origdoublepage\cleardoublepage
\newcommand{\clearemptydoublepage}{%
	\clearpage
	{\pagestyle{empty}\origdoublepage}%
}
```

在需要奇数页开头的小节之间插入`\clearemptydoublepage`命令即可

**Comment by szcf-weiya** [comment]
谢谢！但对“各个小节都需要奇数页开始”的说法存疑，前面的几页确实没考虑这个。但这些页面的 `pagestyle` 是独立于正文的，所以无需 `\newcommand`，只需要单独设定它们的 `pagestyle` 即可，下个版本将修正这个问题。

**Comment by szcf-weiya** [comment]
如果采用  `\cleardoublepage`，则会多出空白页，个人感觉并不好，当然在最后打印论文时需要注意单双页混打，所以我通过定义单独的 `pagestyle` 使得这些页眉处于右边。
