### ISSUE TITLE
Some other pages are needed after the cover?

### ISSUE THREAD

**Issue by joyhuang1225** [szcf-weiya/zju-thesis#3]
Based on the template, some other pages, such as 'A letter of commitment（承诺书）', 'Acknowledgement（致谢）' and 'Abstract' both on Chineses and English should also be included in the thesis.

Besides, the pages of 'Appendix（附录）' and 'Resume（作者简历） '  should be added behind the page of 'Reference'.

**Comment by szcf-weiya** [comment]
The current version is just the main framework. I would add the pages you said in the near future version.

**Comment by szcf-weiya** [comment]
承诺书、致谢及摘要已添加 refer to commit c141c457f5535a20bf673ef5aefb07e5d2b8240e

**Comment by szcf-weiya** [comment]
作者简介已添加 5bfb21c1492946986a198a40fc5f4dab118bd399

**Comment by szcf-weiya** [comment]
附录见 #8
