### ISSUE TITLE
目录章节(chapter)标题之间跟英文没有空格

### ISSUE THREAD

**Issue by joyhuang1225** [szcf-weiya/zju-thesis#5]
跟中文会空格，跟英文没有空格的问题

**Comment by szcf-weiya** [comment]
@joyhuang1225 谢谢丁哥，下次更新改过来。

**Comment by szcf-weiya** [comment]
增加问题描述
![image](https://user-images.githubusercontent.com/13688320/40093138-5c5ceada-58f3-11e8-9519-7b758a4297a4.png)

**Comment by szcf-weiya** [comment]
记录几个坑
1. `\patchcmd` 要在 `titletoc` 加载之前
2. `\patchcmd` 要加上 `\makeatletter`， 所以 #1 中提到`.cls`完全去除`\makeatletter`不可行

**Comment by szcf-weiya** [comment]
后遗症：目录中 chapter 的页码不对齐
