### ISSUE TITLE
目录第二部分“文献综述和开题报告”页面号码自定义

### ISSUE THREAD

**Issue by joyhuang1225** [szcf-weiya/zju-thesis#7]
目录第二部分“文献综述和开题报告”中页面号码和后文无法对应，如何修改呢？

**Comment by szcf-weiya** [comment]
你是指主目录中的页码与第二部分的页码对不齐吗？

**Comment by szcf-weiya** [comment]
在 main.tex 中插入第二部分的[这几行](https://github.com/szcf-weiya/zju-thesis/blob/master/demo/main.tex#L29-L37)中，第一列的数字就是目录中展现的页码，可以自定义。
