### ISSUE TITLE
请问如何添加附录呢？

### ISSUE THREAD

**Issue by joyhuang1225** [szcf-weiya/zju-thesis#8]
正文中的一些引理和定理的证明需要在附录中给出，如何添加附录呢？

**Comment by szcf-weiya** [comment]
refer to commit [1c81b54](https://github.com/szcf-weiya/zju-thesis/commit/1c81b54b18260665e0aae0559b7b98bc9bf86e84).

暂时采用 demo/main.pdf 中的格式（如果有更好的建议，可以修改），具体使用参加 demo/thesis.tex。
